title: Mitchell Phillips # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an academic mathematician pivoting to a career in data science. 
  This is my portfolio of data science projects demonstrating a variety of machine learning tools.  
  I'm an excellent communicator with 3+ years experience teaching college mathematics and strong 
  problem solver with in-depth knowledge of graph theory, linear algebra, statistics, and python data science tools.
  <br><br>
  
  <br><br>
  <a href="https://www.linkedin.com/in/phillipsmj2/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
